"use client";

import * as React from "react";
import { Plus, RefreshCw, Tag } from "lucide-react";
import { AdminShell } from "@/components/admin/admin-shell";
import { Badge, Button, Card, CardContent, CardDescription, CardHeader, CardSkeleton, CardTitle, Field, Input, Modal, Select, Textarea, useToast } from "@/components/ui";
import { apiErrorMessage, type OperationResource, weddingOsApi } from "@/lib/api/client";

const tones: Record<string, string> = { plum: "bg-brand-soft text-brand", coral: "bg-danger-soft text-danger", amber: "bg-warning-soft text-warning", sage: "bg-success-soft text-success", blue: "bg-info-soft text-info" };

export default function LabelsPage() {
  const { toast } = useToast(); const [items, setItems] = React.useState<OperationResource[]>([]); const [loading, setLoading] = React.useState(true); const [error, setError] = React.useState<string | null>(null); const [creating, setCreating] = React.useState(false); const [assigning, setAssigning] = React.useState<OperationResource | null>(null);
  const load = React.useCallback(async () => { setLoading(true); setError(null); try { setItems((await weddingOsApi.platformLabels()).items); } catch (caught) { setError(apiErrorMessage(caught)); } finally { setLoading(false); } }, []);
  React.useEffect(() => {
    const timer = window.setTimeout(() => void load(), 0);
    return () => window.clearTimeout(timer);
  }, [load]);
  return <AdminShell title="Etichete administrative" subtitle="Clasificare internă pentru conturi, evenimente, furnizori și cazuri de suport. Etichetele nu sunt vizibile utilizatorilor." actions={<><Button size="sm" variant="outline" loading={loading} onClick={() => void load()}><RefreshCw className="size-4" />Actualizează</Button><Button size="sm" onClick={() => setCreating(true)}><Plus className="size-4" />Etichetă nouă</Button></>}>
    {loading && !items.length ? <CardSkeleton lines={7} /> : error ? <Card><CardContent className="p-5 text-sm text-danger">{error}</CardContent></Card> : !items.length ? <Card><CardContent className="py-12 text-center"><Tag className="mx-auto size-8 text-faint" /><p className="mt-3 font-semibold">Nu există etichete</p><p className="mt-1 text-sm text-muted">Creează prima etichetă pentru clasificare administrativă.</p></CardContent></Card> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map((item) => { const row = item as Record<string, unknown>; const assignments = Array.isArray(row.assignments) ? row.assignments : []; return <Card key={item.id}><CardHeader><div><CardTitle>{String(row.name)}</CardTitle><CardDescription>{String(row.description ?? "Fără descriere")}</CardDescription></div><span className={`inline-flex size-9 items-center justify-center rounded-lg ${tones[String(row.color)] ?? tones.plum}`}><Tag className="size-4" /></span></CardHeader><CardContent><div className="flex items-center justify-between"><Badge variant="neutral">{assignments.length} alocări</Badge><Button size="sm" variant="outline" onClick={() => setAssigning(item)}>Alocă</Button></div></CardContent></Card>; })}</div>}
    {creating ? <CreateLabelModal onClose={() => setCreating(false)} onSaved={async () => { setCreating(false); toast({ title: "Etichetă creată", variant: "success" }); await load(); }} /> : null}
    {assigning ? <AssignLabelModal label={assigning} onClose={() => setAssigning(null)} onSaved={async () => { setAssigning(null); toast({ title: "Etichetă alocată", variant: "success" }); await load(); }} /> : null}
  </AdminShell>;
}

function CreateLabelModal({ onClose, onSaved }: { onClose: () => void; onSaved: () => Promise<void> }) {
  const [name, setName] = React.useState(""); const [description, setDescription] = React.useState(""); const [color, setColor] = React.useState<"plum" | "coral" | "amber" | "sage" | "blue">("plum"); const [reason, setReason] = React.useState(""); const [busy, setBusy] = React.useState(false); const [error, setError] = React.useState<string | null>(null);
  const submit = async () => { if (name.trim().length < 2 || reason.trim().length < 8) { setError("Completează numele și un motiv de minimum 8 caractere."); return; } setBusy(true); setError(null); try { await weddingOsApi.createPlatformLabel({ name: name.trim(), description: description.trim() || undefined, color, reason: reason.trim() }); await onSaved(); } catch (caught) { setError(apiErrorMessage(caught)); } finally { setBusy(false); } };
  return <Modal open onClose={onClose} title="Etichetă nouă" description="Etichetă internă, limitată la mediul curent." size="sm" footer={<><Button variant="ghost" onClick={onClose}>Anulează</Button><Button loading={busy} onClick={() => void submit()}>Creează</Button></>}><div className="space-y-4"><Field label="Nume" required><Input value={name} onChange={(event) => setName(event.target.value)} /></Field><Field label="Descriere"><Textarea value={description} onChange={(event) => setDescription(event.target.value)} /></Field><Field label="Culoare"><Select value={color} onChange={(event) => setColor(event.target.value as typeof color)}><option value="plum">Prună</option><option value="coral">Coral</option><option value="amber">Chihlimbar</option><option value="sage">Salvie</option><option value="blue">Albastru</option></Select></Field><Field label="Motiv pentru audit" required><Textarea value={reason} onChange={(event) => setReason(event.target.value)} /></Field>{error ? <p role="alert" className="rounded-lg bg-danger-soft p-3 text-sm text-danger">{error}</p> : null}</div></Modal>;
}

function AssignLabelModal({ label, onClose, onSaved }: { label: OperationResource; onClose: () => void; onSaved: () => Promise<void> }) {
  const [type, setType] = React.useState<"USER" | "WORKSPACE" | "VENDOR_ORGANIZATION" | "SUPPORT_CASE">("USER"); const [targetId, setTargetId] = React.useState(""); const [reason, setReason] = React.useState(""); const [busy, setBusy] = React.useState(false); const [error, setError] = React.useState<string | null>(null);
  const submit = async () => { if (!targetId || reason.trim().length < 8) { setError("Completează identificatorul și motivul."); return; } setBusy(true); setError(null); try { await weddingOsApi.assignPlatformLabel(label.id, { targetType: type, targetId: targetId.trim(), reason: reason.trim() }); await onSaved(); } catch (caught) { setError(apiErrorMessage(caught)); } finally { setBusy(false); } };
  return <Modal open onClose={onClose} title={`Alocă ${String(label.name ?? "eticheta")}`} description="Ținta este validată pe server înainte de alocare." size="sm" footer={<><Button variant="ghost" onClick={onClose}>Anulează</Button><Button loading={busy} onClick={() => void submit()}>Alocă</Button></>}><div className="space-y-4"><Field label="Tip țintă"><Select value={type} onChange={(event) => setType(event.target.value as typeof type)}><option value="USER">Utilizator</option><option value="WORKSPACE">Workspace</option><option value="VENDOR_ORGANIZATION">Furnizor</option><option value="SUPPORT_CASE">Caz suport</option></Select></Field><Field label="ID țintă" required hint="UUID-ul exact al resursei."><Input value={targetId} onChange={(event) => setTargetId(event.target.value)} /></Field><Field label="Motiv pentru audit" required><Textarea value={reason} onChange={(event) => setReason(event.target.value)} /></Field>{error ? <p role="alert" className="rounded-lg bg-danger-soft p-3 text-sm text-danger">{error}</p> : null}</div></Modal>;
}
