"use client";

import * as React from "react";
import { Download, Plus, ShieldAlert, UtensilsCrossed } from "lucide-react";
import type { MenuResource } from "@weddingos/contracts";
import { apiErrorMessage, weddingOsApi } from "@/lib/api/client";
import { useWorkspace } from "@/lib/api/workspace-context";
import { Badge, Button, Card, CardContent, EmptyState, Field, Input, Modal, PageHeader, Select, StatCard, Table, TBody, TD, Textarea, TH, THead, TR, useToast } from "@/components/ui";

export default function MenusPage() {
  const { currentWorkspace, bootstrap, demoMode } = useWorkspace(); const { toast } = useToast();
  const [menus, setMenus] = React.useState<MenuResource[]>([]); const [selections, setSelections] = React.useState<Array<Record<string, unknown>>>([]); const [issues, setIssues] = React.useState<Array<Record<string, unknown>>>([]);
  const [editing, setEditing] = React.useState<MenuResource | null | "new">(null); const [loading, setLoading] = React.useState(true); const [error, setError] = React.useState<string | null>(null); const [saving, setSaving] = React.useState(false);
  const capabilities = bootstrap?.membership.capabilities ?? []; const canWrite = capabilities.includes("menu.write");
  const canReadAllergies = capabilities.includes("menu.read_allergies");
  const load = React.useCallback(async () => {
    if (!currentWorkspace || demoMode) { setLoading(false); return; } setLoading(true); setError(null);
    try { const [menuData, selectionData, issueData] = await Promise.all([weddingOsApi.menus(currentWorkspace.id), weddingOsApi.guestMenuSelections(currentWorkspace.id), canReadAllergies ? weddingOsApi.allergyIssues(currentWorkspace.id) : Promise.resolve({ items: [], nextCursor: null })]); setMenus(menuData.items); setSelections(selectionData.items); setIssues(issueData.items); }
    catch (caught) { setError(apiErrorMessage(caught)); } finally { setLoading(false); }
  }, [canReadAllergies, currentWorkspace, demoMode]);
  React.useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);

  const save = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault(); if (!currentWorkspace || demoMode || !editing) return; const data = new FormData(event.currentTarget); const input = { name: String(data.get("name")), description: String(data.get("description") || "") || null, audience: String(data.get("audience")) as "ADULT" | "CHILD" | "ALL", priceMinor: Math.round(Number(data.get("price") || 0) * 100) || null, currency: "RON", vendorNameSnapshot: String(data.get("vendor") || "") || null, status: "ACTIVE" as const, position: editing === "new" ? menus.length : editing.position, courses: [], dietaryTags: String(data.get("tags") || "").split(",").map((item) => item.trim()).filter(Boolean) }; setSaving(true);
    try { if (editing === "new") await weddingOsApi.createMenu(currentWorkspace.id, input); else await weddingOsApi.updateMenu(currentWorkspace.id, editing.id, editing.version ?? 1, input); setEditing(null); toast({ title: editing === "new" ? "Meniu creat" : "Meniu actualizat", variant: "success" }); await load(); }
    catch (caught) { toast({ title: "Meniul nu a fost salvat", description: apiErrorMessage(caught), variant: "error" }); } finally { setSaving(false); }
  };
  const remove = async (menu: MenuResource) => { if (!currentWorkspace || demoMode) return; try { await weddingOsApi.deleteMenu(currentWorkspace.id, menu.id, menu.version ?? 1); toast({ title: "Meniu arhivat", variant: "success" }); await load(); } catch (caught) { toast({ title: "Meniul nu a fost arhivat", description: apiErrorMessage(caught), variant: "error" }); } };
  const exportCatering = async () => { if (!currentWorkspace || demoMode) return; try { const { job } = await weddingOsApi.createCateringExport(currentWorkspace.id, capabilities.includes("menu.read_allergies")); toast({ title: "Export pus în coadă", description: "Datele sensibile sunt incluse numai dacă ai permisiunea necesară.", variant: "info" }); await waitForJob(job.id); const blob = await weddingOsApi.downloadJobArtifact(job.id); downloadBlob(blob, "weddingos-catering.xlsx"); toast({ title: "Export descărcat", variant: "success" }); } catch (caught) { toast({ title: "Exportul a eșuat", description: apiErrorMessage(caught), variant: "error" }); } };

  const selectionCount = (menuId: string) => selections.filter((item) => item.menuId === menuId).length;
  return <div className="mx-auto max-w-7xl space-y-5"><PageHeader title="Meniuri & alergii" description="Selecțiile de meniu ale invitaților, gata de trimis la locație." actions={<><Button variant="outline" size="sm" disabled title="Selecțiile RSVP sunt deja proiectate automat; nu există import separat.">Import RSVP · automat</Button><Button variant="outline" size="sm" disabled={!capabilities.includes("menu.export") || demoMode} onClick={() => void exportCatering()}><Download className="size-3.5" />Export locație</Button><Button size="sm" disabled={!canWrite || demoMode} onClick={() => setEditing("new")}><Plus className="size-4" />Meniu</Button></>} />
    <div className="grid grid-cols-2 gap-3 md:grid-cols-4"><StatCard label="Meniuri active" value={menus.filter((item) => item.status === "active").length} /><StatCard label="Selecții complete" value={selections.length} /><StatCard label="Alergii nerezolvate" value={issues.length} tone={issues.length ? "danger" : undefined} /><StatCard label="Furnizori conectați" value={0} hint="Marketplace-ul nu este încă implementat" /></div>
    {error ? <Card><CardContent className="p-6 text-sm text-danger">{error}</CardContent></Card> : loading ? <Card><CardContent className="p-8 text-sm text-muted">Se încarcă meniurile reale…</CardContent></Card> : menus.length === 0 ? <EmptyState icon={UtensilsCrossed} title="Nu există meniuri" description="Adaugă meniurile care vor fi afișate în formularul RSVP." action={canWrite && !demoMode ? { label: "Adaugă meniu", onClick: () => setEditing("new") } : undefined} /> : <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">{menus.map((menu) => <Card key={menu.id}><CardContent className="p-4"><div className="flex items-start justify-between"><span className="flex size-10 items-center justify-center rounded-xl bg-brand-soft text-brand"><UtensilsCrossed className="size-5" /></span><Badge variant={menu.status === "active" ? "success" : "neutral"}>{menu.status}</Badge></div><h3 className="mt-3 font-semibold text-ink">{menu.name}</h3><p className="mt-1 text-[13px] text-muted">{menu.description || "Fără descriere"}</p><div className="mt-3 flex gap-2"><Badge variant="brand">{selectionCount(menu.id)} selecții</Badge><Badge variant="outline">{menu.audience}</Badge></div>{canWrite && <div className="mt-4 flex gap-2"><Button size="sm" variant="outline" onClick={() => setEditing(menu)}>Editează</Button><Button size="sm" variant="destructive-outline" onClick={() => void remove(menu)}>Arhivează</Button></div>}</CardContent></Card>)}</div>}
    {capabilities.includes("menu.read_allergies") && <Card><CardContent className="p-0"><div className="flex items-center gap-2 border-b border-line p-4"><ShieldAlert className="size-4 text-danger" /><h2 className="text-sm font-semibold">Probleme alergii</h2></div>{issues.length ? <Table minWidth="620px"><THead><TR><TH>Invitat</TH><TH>Alergie</TH><TH>Severitate</TH><TH>Stare</TH></TR></THead><TBody>{issues.map((issue) => <TR key={String(issue.id)}><TD>{String(issue.guestName ?? "Invitat")}</TD><TD>{String(issue.allergy ?? "Raportată")}</TD><TD><Badge variant="danger">{String(issue.severity ?? "unknown")}</Badge></TD><TD>{String(issue.status ?? "unreviewed")}</TD></TR>)}</TBody></Table> : <p className="p-5 text-sm text-muted">Nu există probleme de alergii nerezolvate.</p>}</CardContent></Card>}
    <Modal open={Boolean(editing)} onClose={() => setEditing(null)} title={editing === "new" ? "Meniu nou" : "Editează meniul"}><form className="space-y-4" onSubmit={save}><Field label="Nume" required><Input name="name" required defaultValue={editing !== "new" && editing ? editing.name : ""} /></Field><Field label="Descriere"><Textarea name="description" defaultValue={editing !== "new" && editing ? editing.description ?? "" : ""} /></Field><div className="grid grid-cols-2 gap-3"><Field label="Audiență"><Select name="audience" defaultValue={editing !== "new" && editing ? editing.audience.toUpperCase() : "ALL"}><option value="ALL">Toți</option><option value="ADULT">Adulți</option><option value="CHILD">Copii</option></Select></Field><Field label="Preț RON"><Input name="price" type="number" min="0" defaultValue={editing !== "new" && editing && editing.priceMinor ? editing.priceMinor / 100 : ""} /></Field></div><Field label="Furnizor (snapshot)"><Input name="vendor" /></Field><Field label="Etichete dietetice" hint="Separate prin virgulă"><Input name="tags" /></Field><div className="flex justify-end gap-2"><Button type="button" variant="ghost" onClick={() => setEditing(null)}>Renunță</Button><Button type="submit" disabled={saving}>Salvează</Button></div></form></Modal>
  </div>;
}

async function waitForJob(jobId: string) { for (let attempt = 0; attempt < 60; attempt += 1) { const job = await weddingOsApi.job(jobId); if (job.status === "completed") return; if (["failed", "dead_letter", "cancelled"].includes(job.status)) throw new Error(job.error?.message ?? "Job eșuat"); await new Promise((resolve) => window.setTimeout(resolve, 500)); } throw new Error("Exportul nu s-a încheiat la timp"); }
function downloadBlob(blob: Blob, name: string) { const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = name; anchor.click(); URL.revokeObjectURL(url); }
